### ISSUE TITLE
Can you provide a demonstration?

### ISSUE THREAD

**Issue by dunce1** [Gid-CTO/OverlappingMarkerSpiderfier-java#2]
Firstly, thank you for sharing this code. I am having trouble getting the Overlapping Marker Spiderfier to work with Android. I followed the instructions and wrote one line to instantiate it: OverlappingMarkerSpiderfier oms = new OverlappingMarkerSpiderfier(mMap);

However, when I click the two markers that have the same coordinates, nothing happens. Do I have to do something else other than just instantiate it? I am using android-maps-extensions and have included the java file with the updated package name.

Also, I was wondering if it would be possible for you to post up a working demo code so I can compare my code. It would also be a big help to other people as well who may have difficulty getting it to work on their end based on the code and instructions alone.

**Comment by Dev-iL** [comment]
Hi dunce1, 
Thanks for pointing out that the instructions were incomplete!

After instantiating the `oms` you should pass it the `Marker` object like so: `oms.spiderListener(marker);`

Below is a piece of the code I used that controls spiderfication starting a certain zoom level (a method I highly recommend using):

```
// We need to figure out if it was a seperate marker or a cluster marker
if (marker.isCluster()) {
    if (mMap.getCameraPosition().zoom >= SPIDERFICATION_ZOOM_THRSH)
    oms.spiderListener(marker); // That's where the magic happens
    else {
        mMap.animateCamera(CameraUpdateFactory.newLatLngZoom(
                marker.getPosition(),
                mMap.getCameraPosition().zoom + dynamicZoomLevel()));
        updateClusteringRadius();
        }
    return true;
}

private void updateClusteringRadius() {
    if (clusterSettings == null) {
        clusterSettings = new ClusteringSettings();
        clusterSettings.addMarkersDynamically(true);
        clusterSettings.clusterSize(clusterRadiusCalculation());
        ClusterOptionsProvider provider = new ClusterOptionsProvider() {
            @Override
            public ClusterOptions getClusterOptions(List<Marker> markers) {
                return new ClusterOptions().icon(BitmapDescriptorFactory
                        .fromResource(R.drawable.app_logo_gray));
            }
        };
        mMap.setClustering(clusterSettings.clusterOptionsProvider(provider));
    } else if (mMap.getCameraPosition().zoom>13F){
        //placeholder for some logic
    } else {
        clusterSettings.clusterSize(clusterRadiusCalculation());
    }
}
```

Please let me know if this solves your problem!
Iliya.

**Comment by dunce1** [comment]
Thanks Iliya! What should I put in the dynamicZoomLevel() and clusterRadiusCalculation() methods? 

Also for this part:

```
// We need to figure out if it was a seperate marker or a cluster marker
if (marker.isCluster()) {
    if (mMap.getCameraPosition().zoom >= SPIDERFICATION_ZOOM_THRSH)
    oms.spiderListener(marker); // That's where the magic happens
    else {
        mMap.animateCamera(CameraUpdateFactory.newLatLngZoom(
                marker.getPosition(),
                mMap.getCameraPosition().zoom + dynamicZoomLevel()));
        updateClusteringRadius();
        }
    return true;
}
```

I assume this is part of a method? I see you have a return statement near the end. I have used this code as so:

```
private boolean markerIsCluster(Marker marker) {

    if (marker.isCluster()) {
        if (mMap.getCameraPosition().zoom >= 15) //I will play around with this. I assume the SPIDERFICATION_ZOOM_THRSH is constant and never changes.
            oms.spiderListener(marker); // That's where the magic happens
        else {
            mMap.animateCamera(CameraUpdateFactory.newLatLngZoom(
                    marker.getPosition(),
                    mMap.getCameraPosition().zoom + dynamicZoomLevel()));
            updateClusteringRadius();
        }
        return true;
    }
  return false;
}
```

Thanks once again.

**Comment by Dev-iL** [comment]
Sorry for the mess, I didn't touch this code for a very long time.... If you run into more problems you could also take a look at the documentation of the original JS library (I tried keeping the method and variable names the same).

Please see the code below:

```
mMap.setOnMarkerClickListener(new OnMarkerClickListener() {
    @Override
    public boolean onMarkerClick (Marker marker){
        if (marker.isCluster()) {
            if (mMap.getCameraPosition().zoom >= 15) //I will play around with this. I assume the SPIDERFICATION_ZOOM_THRSH is constant and never changes.
                oms.spiderListener(marker); // That's where the magic happens
            else {
                mMap.animateCamera(CameraUpdateFactory.newLatLngZoom(
                        marker.getPosition(),
                        mMap.getCameraPosition().zoom + dynamicZoomLevel()));
                updateClusteringRadius();
            }
            return true;
        }
        return false;
    }
}
```

`dynamicZoomLevel()` is basically where you define the zoom step size, this is what I used (to make it a function of the current zoom level):

```
private float dynamicZoomLevel() {
    float currZoomLvl = mMap.getCameraPosition().zoom;
    final float minZoomStepAtZoom = 17.3F, minZoomStep = 1.8F;
    final float maxZoomStepAtZoom = 7F, maxZoomStep = 2.8F;

    if (currZoomLvl >= minZoomStepAtZoom)
        return minZoomStep;
    else if (currZoomLvl <= maxZoomStepAtZoom)
        return maxZoomStep;
    else
        // simple interpolation:
        return (currZoomLvl - maxZoomStepAtZoom)
                * (maxZoomStep - minZoomStep)
                / (maxZoomStepAtZoom - minZoomStepAtZoom) + maxZoomStep;
}
```

Finally, `clusterRadiusCalculation()`, that IIRC, controls the radius of the spiderfied markers in case of a spiral is:

```
private int clusterRadiusCalculation() {
    final int minRad = 0, maxRad = 150;
    final float minRadZoom = 10F, maxRadZoom = 7.333F;

    if (mMap.getCameraPosition().zoom >= minRadZoom) {

        return minRad;

    } else if (mMap.getCameraPosition().zoom <= maxRadZoom)
        return maxRad;
    else
        // simple interpolation:
        return (int) (maxRad - (maxRadZoom - mMap.getCameraPosition().zoom)
                * (maxRad - minRad) / (maxRadZoom - minRadZoom));
}
```

**Comment by dunce1** [comment]
Sorry, forgot about one more method that's missing:
updateClusteringRadius();

Thanks again for all the help!

**Comment by Dev-iL** [comment]
```
private void updateClusteringRadius() {
    if (clusterSettings == null) {
        clusterSettings = new ClusteringSettings();
        clusterSettings.addMarkersDynamically(true);
        clusterSettings.clusterSize(clusterRadiusCalculation());
        ClusterOptionsProvider provider = new ClusterOptionsProvider() {
            @Override
            public ClusterOptions getClusterOptions(List<Marker> markers) {
                return new ClusterOptions().icon(BitmapDescriptorFactory
                        .fromResource(R.drawable.app_logo_gray));
            }
        };
        mMap.setClustering(clusterSettings.clusterOptionsProvider(provider));
    } else if (mMap.getCameraPosition().zoom>13F){

    } else {
        clusterSettings.clusterSize(clusterRadiusCalculation());
    }

}
```

**Comment by dunce1** [comment]
Amazing!!! It works! I am so excited! Tested on the first Samsung Galaxy S (non-emulator). Sometimes the lines are a bit off from the centre of where they expand, but it's nothing! Probably needs a bit more testing to make sure there's no crashes/exceptions. Also, the animation is a great addition! It's so smooth. Thank you so much, you have done an amazing job good sir and thank you for sharing this with GitHub! We should definitely get the instructions updated and put a demo up with working code. I think this project will be very useful to a lot of people. I am new to GitHub (only joined because I wanted to ask you a question and I was desperate for answers) however, I would love to contribute to this project anyway I can.

Edit: I realized that one of the lines were off center because one of the locations were close to the other markers which had the same latitude and longitude. So it's not a bug. Cheers! Thanks once again!

**Comment by Alialiazhar** [comment]
Please tell OverlappingMarkerSpiderfier has two parameters (GoogleMap gm, Object ... varArgs) what is object..varargs please tell me as soon as possible in android

**Comment by Dev-iL** [comment]
@Alialiazhar - Theoretically, these are key-value pairs you can pass as an input to the function to control various aspects of "spiderfication". At the _current_ state of the code, they do not affect the actual private properties of `OverlappingMarkerSpiderfier`, and instead these properties must be hard-coded. See lines 44-50 for a list of arguments, and 57-82 for explanations what each one means.

**Comment by sagar676** [comment]
can anyone send the whole coad of overlapping marker my email id is sagarpandit801@gmail.com

**Comment by Dev-iL** [comment]
@sagar676 - Thank you for your interest in this library! 

Although the app for which I made this (and the only app I used it in) is no longer available, I cannot upload its whole sources. This means I will need to create a minimal working example in order to fulfill this request. It could take an unknown amount of time - anywhere from a few days to a month.

Consider that the snippets found in this issue should be sufficient to get it working. Alternatively, perhaps @dunce1 can upload their result of piecing together the code (and maybe also some later enhancements... :) ).

To whomever it may concern - if you have short, working example, feel free to submit a pull request and it will be added.

**Comment by sagar676** [comment]
thank you for your response i will try to make it working in small module if i got any issue i will reply you back ...

**Comment by sagar676** [comment]
thank you for your response i will try to make it working in small module
if i got any issue i will reply you back ...

**Comment by Dev-iL** [comment]
@sagar676 I have just uploaded a working sample.

**Comment by sagar676** [comment]
thanx Dev-iL thank you very much your example helped me lot...its working perfectly fine for me
